### ISSUE TITLE
Suddenly Stopped Working

### ISSUE THREAD

**Issue by snichol67** [corbinbs/solarshed#15]
I am all but certain that this is not an issue with Solar Shed.  That being said, I had a perfectly working system running on a Raspberry Pi, everything was being stored in Prometheus, charted with Grafana.  Then today, I reconnected my Renogy Bluetooth module just to see what the Renogy DC Home app could offer, just out of curiosity.  Since I've done that, when I reconnect the Raspberry Pi Solar Shed server (and more specifically the MinimalModbus) library is reporting errors to the effect of:

`Nov 03 13:22:19 raspberrypi python[445]:   File "/home/pi/.local/lib/python2.7/site-packages/minimalmodbus.py", line 930, in _communicate`
`Nov 03 13:22:19 raspberrypi python[445]:     raise IOError('No communication with the instrument (no answer)')`
`Nov 03 13:22:19 raspberrypi python[445]: IOError: No communication with the instrument (no answer)`

The software version on the charge controller is reporting device version V3.0.1 (I'm seeing this through the Renogy BT app on my phone).  I'm starting to think that running the Renogy DC Home app might have updated the firmware on the device so that it somehow blocks requests over the serial port from unknown sources.  Also just curious what the software version on your charge controller indicates?

**Comment by Robot845** [comment]
Was this ever resolved? This just happened to me, I was working on an unrelated project and it just stopped working.

OSError: No communication with the instrument (no answer)
problem updating gauges
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/solarshed/server.py", line 33, in <module>
    battery_percentage_gauge.set(controller.battery_percentage())
  File "/home/pi/.local/lib/python3.9/site-packages/solarshed/controllers/renogy_rover.py", line 80, in battery_percentage
    return self.read_register(256) & 0x00ff
  File "/home/pi/.local/lib/python3.9/site-packages/minimalmodbus.py", line 258, in read_register
    return self._genericCommand(functioncode, registeraddress, numberOfDecimals=numberOfDecimals, signed=signed)
  File "/home/pi/.local/lib/python3.9/site-packages/minimalmodbus.py", line 697, in _genericCommand
    payloadFromSlave = self._performCommand(functioncode, payloadToSlave)
  File "/home/pi/.local/lib/python3.9/site-packages/minimalmodbus.py", line 795, in _performCommand
    response = self._communicate(request, number_of_bytes_to_read)
  File "/home/pi/.local/lib/python3.9/site-packages/minimalmodbus.py", line 930, in _communicate
    raise IOError('No communication with the instrument (no answer)')

**Comment by corbinbs** [comment]
Hi folks - I've not encountered this one before.    The Raspberry Pi I had installed in my "original" solar shed trailer just expired -- so I might try to do a "fresh setup" to a) document it and b) see if I encounter anything like this one.

If I find anything helpful, I'll report back
